### ISSUE TITLE
请问如何获取gradio外链分享

### ISSUE THREAD

**Issue by ElainaFanBoy** [Alpaca4610/nonebot-plugin-audiocraft#1]
官方仓库里给的colab代码里好像没有分享的部分

**Comment by Alpaca4610** [comment]
> 官方仓库里给的colab代码里好像没有分享的部分

导入完模型之后，在colab里面新增一个代码块，克隆官方的代码仓库后修改app.py，在launch部分加上share=True，然后启动app.py即可

**Comment by ElainaFanBoy** [comment]
> > 官方仓库里给的colab代码里好像没有分享的部分
> 
> 导入完模型之后，在colab里面新增一个代码块，克隆官方的代码仓库后修改app.py，在launch部分加上share=True，然后启动app.py即可

感谢！
