### ISSUE TITLE
本地部署 audiocraft后使用插件报错

### ISSUE THREAD

**Issue by JustinHuangber** [Alpaca4610/nonebot-plugin-audiocraft#4]
聊天环境报错：Expected 0 arguments, got 8

**Comment by Alpaca4610** [comment]
参考这里：https://github.com/Alpaca4610/nonebot-plugin-audiocraft/issues/3#issuecomment-1596937749

**Comment by xmaaa666** [comment]
现在还是不行

**Comment by Alpaca4610** [comment]
> 
可以提供一下audiocraft WEB页面底部的use API页面的截图吗？
